// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using illiminatado_exam.Data;

#nullable disable

namespace illiminatado_exam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327134855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("illiminatado_exam.Model.OtReg", b =>
                {
                    b.Property<int>("payroll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("payroll"));

                    b.Property<int>("cost_center")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.Property<string>("file_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("freq")
                        .HasColumnType("integer");

                    b.Property<DateTime>("from")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("je_cost_center")
                        .HasColumnType("integer");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ot_amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ot_and_np_amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ot_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ot_hours")
                        .HasColumnType("numeric");

                    b.Property<int>("ot_minutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("ot_np2_amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ot_np2_hours")
                        .HasColumnType("integer");

                    b.Property<int>("ot_np2_minutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("ot_np_amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ot_np_hours")
                        .HasColumnType("numeric");

                    b.Property<int>("ot_np_minutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("ot_rate")
                        .HasColumnType("numeric");

                    b.Property<string>("pay_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("pay_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("recur_end")
                        .HasColumnType("integer");

                    b.Property<int>("recur_start")
                        .HasColumnType("integer");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("system_np_hours")
                        .HasColumnType("numeric");

                    b.Property<string>("system_np_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("system_ot_hours")
                        .HasColumnType("numeric");

                    b.Property<string>("system_ot_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("to")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("payroll");

                    b.ToTable("ot_reg");
                });

            modelBuilder.Entity("illiminatado_exam.Model.PayReg", b =>
                {
                    b.Property<int>("payroll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("payroll_id"));

                    b.Property<string>("adjustments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("att_deduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bank_acct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bank_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("basic_salary")
                        .HasColumnType("numeric");

                    b.Property<int>("comment_field")
                        .HasColumnType("integer");

                    b.Property<string>("cost_center")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("daily_rate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("date_employed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("date_terminated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("deductions")
                        .HasColumnType("numeric");

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("employee_mcr")
                        .HasColumnType("numeric");

                    b.Property<int>("employee_pag_ibig")
                        .HasColumnType("integer");

                    b.Property<int>("employee_sss")
                        .HasColumnType("integer");

                    b.Property<int>("employer_ec")
                        .HasColumnType("integer");

                    b.Property<decimal>("employer_mcr")
                        .HasColumnType("numeric");

                    b.Property<string>("employer_pag_ibig")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("employer_sss")
                        .HasColumnType("integer");

                    b.Property<string>("error_field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("exchange_rate")
                        .HasColumnType("integer");

                    b.Property<string>("file_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("from")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("gross_income")
                        .HasColumnType("numeric");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("loan_payments")
                        .HasColumnType("numeric");

                    b.Property<int>("monthly_allow")
                        .HasColumnType("integer");

                    b.Property<decimal>("monthly_salary_rate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("mtd_basic")
                        .HasColumnType("numeric");

                    b.Property<decimal>("mtd_ec_employer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("mtd_gross")
                        .HasColumnType("numeric");

                    b.Property<decimal>("mtd_mcr_employee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("mtd_mcr_employer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("mtd_ntx")
                        .HasColumnType("numeric");

                    b.Property<int>("mtd_pag_ibig_employee")
                        .HasColumnType("integer");

                    b.Property<int>("mtd_pag_ibig_employer")
                        .HasColumnType("integer");

                    b.Property<int>("mtd_sss_employee")
                        .HasColumnType("integer");

                    b.Property<decimal>("mtd_sss_employer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("mtd_wh_tax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("net_salary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("net_salary_after_tax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("other_ntx_income")
                        .HasColumnType("numeric");

                    b.Property<string>("overtime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pay_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("pay_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("payment_freq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("payment_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("payroll_cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("previous_ytd_bon_13th_nt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("previous_ytd_bon_13th_tx")
                        .HasColumnType("numeric");

                    b.Property<decimal>("previous_ytd_gross")
                        .HasColumnType("numeric");

                    b.Property<decimal>("previous_ytd_mcr")
                        .HasColumnType("numeric");

                    b.Property<int>("previous_ytd_pag_ibig")
                        .HasColumnType("integer");

                    b.Property<decimal>("previous_ytd_sss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("previous_ytd_witholding")
                        .HasColumnType("numeric");

                    b.Property<string>("salary_rate_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tax_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tax_table")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("taxable_income")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("to")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("witholding_tax")
                        .HasColumnType("numeric");

                    b.HasKey("payroll_id");

                    b.ToTable("pay_regs");
                });

            modelBuilder.Entity("illiminatado_exam.Model.TimeAttendance", b =>
                {
                    b.Property<int>("payroll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("payroll_id"));

                    b.Property<decimal>("absent_days")
                        .HasColumnType("numeric");

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("lwop_days")
                        .HasColumnType("numeric");

                    b.Property<decimal>("nit_diff")
                        .HasColumnType("numeric");

                    b.Property<decimal>("otherlv_days")
                        .HasColumnType("numeric");

                    b.Property<decimal>("reg_ot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("reg_otNp_hr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("sl_days")
                        .HasColumnType("numeric");

                    b.Property<decimal>("underTime_hrs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("vl_days")
                        .HasColumnType("numeric");

                    b.HasKey("payroll_id");

                    b.ToTable("time_attend");
                });
#pragma warning restore 612, 618
        }
    }
}
